#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/opt/nodejs/node-v22.19.0-linux-x64/bin/node" "/home/user/.vscode/data/User/globalStorage/github.copilot-chat-bas/debugCommand/copilotDebugCommand.js" "openvscode-server://github.copilot-chat" "code --openExternal " "$@"