/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTravelListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Agency");
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Customer");
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Status");
        });

        opaTest("Add semantic key properties to filter bar", function (Given, When, Then) {
            Then.onTheTravelListGenerated.onFilterBar().iOpenFilterAdaptation();
            When.onTheTravelListGenerated.onFilterBar().iAddAdaptationFilterField("Travel");
            Then.onTheTravelListGenerated.onFilterBar().iConfirmFilterAdaptation();
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Travel");
            // Then.onTheTravelListGenerated.onFilterBar().iChangeFilterField("Travel");
            // Then.onTheTravelListGenerated.onFilterBar().iExecuteSearch();
            // Then.onTheTravelListGenerated.onTable().iCheckRows();
            // Then.onTheTravelListGenerated.onTable().iSelectRows(0);
            // Then.onTheTravelListGenerated.onTable().iCheckAction("<Action Name>", { enabled: true });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheTravelListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheTravelListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTravelListGenerated.onTable().iCheckColumns(undefined, {"TravelID":{"header":"Travel"},"AgencyID":{"header":"Agency"},"CustomerID":{"header":"Customer"},"OverallStatus":{"header":"Status"},"LocalLastChangedAt":{"header":"Last Changed At"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheTravelListGenerated.onTable().iCheckRows();

            When.onTheTravelListGenerated.onTable().iPressRow(0);
            Then.onTheTravelObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});