/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelObjectPageObjectPage journey");

        opaTest("Navigate to TravelObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheTravelListGenerated.onTable().iCheckRows();
            When.onTheTravelListGenerated.onTable().iPressRow(0);

            Then.onTheTravelObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "TravelHeaderOverallStatus" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTravelObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheTravelObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheTravelObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            When.onTheTravelObjectPageGenerated.iPressSectionIconTabFilterButton("Booking");
            Then.onTheTravelObjectPageGenerated.iCheckSection({ section: "Booking" });
            Then.onTheTravelObjectPageGenerated.onTable({ property: "_Booking" }).iCheckColumns({"_Carrier/AirlinePicURL":{"header":" "},"BookingID":{"header":"Booking Number"},"BookingDate":{"header":"Booking Date"},"CustomerID":{"header":"Customer"},"CarrierID":{"header":"Airline"},"ConnectionID":{"header":"Flight Number"},"FlightDate":{"header":"Flight Date"},"FlightPrice":{"header":"Flight Price"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});